version: "3.8"
services:
  roll-of-arms:
    build: .
    restart: unless-stopped
    env_file: '.env'
    ports:
      - '8080:8080' 
    logging:
      driver: local
      options:
        max-size: '10m'